#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.3.5.1 on Tue Aug 29 15:58:12 2006
"""该模块是定义gsstools的主界面
"""

import wx
import locale,os
import geosings.core.system.UseGetText
from geosings.core.system import GetThisDir
from geosings.core.system.GssConfDict import GSSCONF
from geosings.tools.GTTreePanel import GTFrame

syslocale = locale.getdefaultlocale()
thisdir = GetThisDir(__file__)

#def ExecConf():
#    thisdir = GetThisDir(__file__)
#    file = open(os.path.join(thisdir,'tools.conf'))
#    fc = file.read()
#    file.close()
#    exec(fc)


def GetToolsFrame():
    #ExecConf()
    return GTFrame(None, -1, "")

def run():
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = GetToolsFrame()
    frame_1.SetSize((200,500))
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()

if __name__ == "__main__":
    run()
