#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.4.1 on Fri May 12 20:13:53 2006

"""
该模块定义程序主框架
"""

import wx

from geosings.ui.core.MainImage import GetMainIcon

from PyMainPanel import *
from MyToolBar import CreateMainToolBar
from MyMenuBar import CreateMainMenuBar


class MainFrame(wx.Frame):
    """程序主框架
    """
    def __init__(self, *args, **kwds):
        """初始化框架
        """
        from UISettings import mainMenuConf,mainToolConf
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        #self.panel = MainPanel(self)
        #img = wx.Image("geosings.png",wx.BITMAP_TYPE_PNG)
        #self.icon = wx.IconFromBitmap(img.Scale(16,16).
        #    ConvertToBitmap())
        self.icon = GetMainIcon()
        self.menubar = None; self.toolbar = None
        self.panel = CreateMainPanel(self)

        self.optid = 0 #用来存储ui的操作id
        self.menubar = CreateMainMenuBar(self,mainMenuConf)
        self.toolbar = CreateMainToolBar(self,mainToolConf)

        self.__set_properties()
        self.__do_layout()
        self.panel.SetFocus()
    
    def GetToolBar(self):
        return self.toolbar
    def GetMenuBar(self):
        return self.menubar

    def __set_properties(self):
        """设置属性
        """
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("(Geo)xS,Show,I,Nice,Gold")
        self.SetIcon(self.icon)
        self.SetSize((720, 540))
        self.SetMenuBar(self.menubar)
        self.SetToolBar(self.toolbar)
        # end wxGlade

    def __do_layout(self):
        """设置布局
        """
        # begin wxGlade: MainFrame.__do_layout
        sizermain = wx.BoxSizer(wx.VERTICAL)
        sizermain.Add(self.panel, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizermain)
        self.Layout()
        # end wxGlade
    def OnMouse(self, evt):
        """响应鼠标事件
        @type evt: wxEvent
        @param evt: 鼠标事件
        """
        if evt.ButtonDown():
            self.SetFocus()
        #print 'mouse'

# end of class MainFrame
def run(app):
    """运行主程序
    @type app: wx.PySimpleApp
    @param app: wx的App对象
    """
    #app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainframe = MainFrame(None, -1, "")
    app.SetTopWindow(mainframe)
    mainframe.Show()
    app.MainLoop()
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    run(app)
